# Generated by Django 4.0.2 on 2022-02-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(max_length=100, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_points', models.IntegerField(max_length=20)),
                ('user_email', models.EmailField(max_length=100)),
            ],
        ),
    ]
