# Generated by Django 4.0.2 on 2022-02-09 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Game_Users',
        ),
    ]
