# Generated by Django 4.0.2 on 2022-02-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_users_game_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_users',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='game_users',
            name='user_points',
            field=models.IntegerField(),
        ),
    ]
