# Generated by Django 4.0.2 on 2022-02-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_game_users_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raining',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_points', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['user_points'],
            },
        ),
        migrations.DeleteModel(
            name='Game_Users',
        ),
    ]
