# Generated by Django 4.0.2 on 2022-02-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_raining_delete_game_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanoCoordinates',
            fields=[
                ('pano_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pano_longitude', models.FloatField()),
                ('pano_latitude', models.FloatField()),
            ],
        ),
    ]
