# Generated by Django 4.0.2 on 2022-02-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_delete_raining'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
    ]
